import axios, { AxiosError } from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { FiUserPlus } from "react-icons/fi";
import styled from "styled-components";
import ContentCard from "../../Components/ContentCard";
import ClientRegistration from "../../Components/Registration/Client";
import TitleComponent from "../../Components/Title";
import { Client } from "../../Models/Client";
import LayoutTemplate from "../../Templates/Layout";

const Wrapper = styled.div`
    padding: 24px;
`;

interface ICreateClientProps {
    clients?: Client[]
}

const CreateClient: NextPage<ICreateClientProps> = ({ clients }) => {
    return (
        <>
            <Head>
                <title>Rental Company</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <LayoutTemplate>
                <Wrapper>
                    <TitleComponent>
                        <FiUserPlus /> Cadastrar novo Cliente
                    </TitleComponent>
                    <ContentCard responsive>
                        <ClientRegistration />
                    </ContentCard>
                </Wrapper>
            </LayoutTemplate>
        </>
    );
};

CreateClient.getInitialProps = async () => {
    const clients = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/client`)
        .then(res => res.data)
        .catch((res: AxiosError) => null);

    return { clients }
}

export default CreateClient;
