import axios, { AxiosError } from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { HiOutlineClipboardList } from "react-icons/hi";
import styled from "styled-components";
import ContentCard from "../../Components/ContentCard";
import ClientsListTable from "../../Components/Table/ClientsListTable";
import TitleComponent from "../../Components/Title";
import { Client } from "../../Models/Client";
import LayoutTemplate from "../../Templates/Layout";

const Wrapper = styled.div`
    padding: 24px 24px;
    overflow-y: scroll;
`;

interface IClientsListProps {
    clients?: Client[]
}

const ClientsList: NextPage<IClientsListProps> = ({ clients }) => {
    return (
        <>
            <Head>
                <title>Rental Company</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <LayoutTemplate>
                <Wrapper>
                    <TitleComponent>
                        <HiOutlineClipboardList /> Lista de Clientes Cadastrados
                    </TitleComponent>
                    <ContentCard>
                        <ClientsListTable clients={clients} />
                    </ContentCard>
                </Wrapper>
            </LayoutTemplate>
        </>
    );
};

ClientsList.getInitialProps = async () => {
    const clients = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/client`)
        .then(res => res.data)
        .catch((res: AxiosError) => null);

    return { clients }
}

export default ClientsList;
