version: "3.1"

services:
  database_backend:
    image: mysql:5.7
    ports:
      - 3306:3306
    hostname: database_backend
    environment:
      MYSQL_ROOT_PASSWORD: backend
      MYSQL_DATABASE: admin
      MYSQL_USER: backend
      MYSQL_PASSWORD: backend
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - rental_company_network

  app_backend:
    build:
      context: .
      dockerfile: APP_Dockerfile
    depends_on:
      - database_backend
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      # - 80:80 # Para ASPNETCORE_ENVIRONMENT: Production
      - 5001:80 # Para ASPNETCORE_ENVIRONMENT: Development
    networks:
      - rental_company_network

# volumes:
#   db-volume:
#     driver: local
  
networks:
  rental_company_network:
    driver: bridge