import axios, { AxiosError } from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { HiOutlineClipboardList } from "react-icons/hi";
import styled from "styled-components";
import ContentCard from "../../Components/ContentCard";
import MoviesListTable from "../../Components/Table/MoviesListTable";
import TitleComponent from "../../Components/Title";
import { Movie } from "../../Models/Movie";
import LayoutTemplate from "../../Templates/Layout";

const Wrapper = styled.div`
    padding: 24px;
`;

interface IClientsListProps {
    movies?: Movie[]
}

const MoviesList: NextPage<IClientsListProps> = ({ movies }) => {
    return (
        <>
            <Head>
                <title>Rental Company</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <LayoutTemplate>
                <Wrapper>
                    <TitleComponent>
                        <HiOutlineClipboardList /> Lista de Filmes Cadastrados
                    </TitleComponent>
                    <ContentCard>
                        <MoviesListTable movies={movies} />
                    </ContentCard>
                </Wrapper>
            </LayoutTemplate>
        </>
    );
};

MoviesList.getInitialProps = async () => {
    const movies = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/movie`)
        .then(res => res.data)
        .catch((res: AxiosError) => null);

    return { movies }
}

export default MoviesList;
