import Head from "next/head";
import React from "react";
import ContentCard from "../../Components/ContentCard";
import TitleComponent from "../../Components/Title";
import LayoutTemplate from "../../Templates/Layout";
import WrapperComponent from "../../Components/Wrapper";
import UploadComponent from "../../Components/UploadComponent";
import { AiOutlineCloudUpload } from "react-icons/ai";

const UploadListMovies = () => {
    return (
        <>
            <Head>
                <title>Rental Company</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <LayoutTemplate>
                <WrapperComponent>
                    <TitleComponent>
                        <AiOutlineCloudUpload /> Importar dados de filmes em planilha no formato .CSV
                    </TitleComponent>
                    <ContentCard>
                        <UploadComponent
                            title="Clique aqui ou arraste seu arquivo .xlsx nesta área para fazer upload"
                            subTitle={
                                `Insira dados dos filmes, como "Id", "Titulo", "ClassificacaoIndicativa, "Lancamento" separados por ; para cadastra-los.`
                            }
                        />
                    </ContentCard>
                </WrapperComponent>
            </LayoutTemplate>
        </>    
    );
};

export default UploadListMovies;
