import axios, { AxiosError } from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { MdOutlineAssignmentReturned } from "react-icons/md";
import styled from "styled-components";
import ContentCard from "../../Components/ContentCard";
import RentalRegistration from "../../Components/Registration/Rental";
import TitleComponent from "../../Components/Title";
import { Client } from "../../Models/Client";
import { Movie } from "../../Models/Movie";
import LayoutTemplate from "../../Templates/Layout";

const Wrapper = styled.div`
    padding: 24px;
`;

interface IClientsListProps {
    clients: Client[];
    movies: Movie[];
}

const ClientsList: NextPage<IClientsListProps> = ({ clients, movies }) => {
    return (
        <>
            <Head>
                <title>Rental Company</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <LayoutTemplate>
                <Wrapper>
                    <TitleComponent>
                        <MdOutlineAssignmentReturned /> Fazer nova locação
                    </TitleComponent>
                    <ContentCard responsive>
                        <RentalRegistration
                            clients={clients} 
                            movies={movies}
                        />
                    </ContentCard>
                </Wrapper>
            </LayoutTemplate>
        </>
    );
};

ClientsList.getInitialProps = async () => {
    const clients = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/client`)
        .then(res => res.data)
        .catch((res: AxiosError) => []);
    
    const movies = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/movie`)
        .then(res => res.data)
        .catch((res: AxiosError) => []);

    return { clients, movies }
}

export default ClientsList;
