import axios, { AxiosError } from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { HiOutlineClipboardList } from "react-icons/hi";
import styled from "styled-components";
import ContentCard from "../../Components/ContentCard";
import RentalListTable from "../../Components/Table/RentalListTable";
import TitleComponent from "../../Components/Title";
import { Rental } from "../../Models/Rental";
import LayoutTemplate from "../../Templates/Layout";

const Wrapper = styled.div`
    padding: 24px;
`;

interface IClientsListProps {
    locations?: Rental[]
}

const LocationsList: NextPage<IClientsListProps> = ({ locations }) => {
    return (
        <>
            <Head>
                <title>Rental Company</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <LayoutTemplate>
                <Wrapper>
                    <TitleComponent>
                        <HiOutlineClipboardList /> Lista de Locações realizadas
                    </TitleComponent>
                    <ContentCard>
                        <RentalListTable locations={locations} />
                    </ContentCard>
                </Wrapper>
            </LayoutTemplate>
        </>
    );
};

LocationsList.getInitialProps = async () => {
    const locations = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/location`)
        .then(res => res.data)
        .catch((res: AxiosError) => null);

    return { locations }
}

export default LocationsList;
