import type { NextPage } from "next";
import Head from "next/head";
import LayoutTemplate from "../Templates/Layout";
import ContentCard from "../Components/ContentCard";
import styled from "styled-components";
import axios from "axios";
import { Button, Empty } from "antd";
import TitleComponent from "../Components/Title";
import { TbFileDownload } from "react-icons/tb";

interface IInitialPageProps {
    
}

const Wrapper = styled.div`
    padding: 24px;
`;

const ExportReportData: NextPage<IInitialPageProps> = ({  }) => {

    const handleOnDownloadReport = async () => {
        await axios.get(
            `${process.env.NEXT_PUBLIC_API_URL}/report/generate-report`,
            { responseType: "blob" }
        ).then((res) => {            
            let fileName = res.headers["content-disposition"].match(/filename=(.*);/)![1];
            const url = window.URL.createObjectURL(new Blob([res.data], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }));
            const link = document.createElement('a');
            link.href = url;
            link.setAttribute('download', fileName);
            document.body.appendChild(link);
            link.click();
        });
    }

    return (
        <>
            <Head>
                <title>Rental Company</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <LayoutTemplate>
                <Wrapper>
                    <TitleComponent>
                        <TbFileDownload /> Exportar relatório em planilhas no formato .CSV
                    </TitleComponent>
                    <ContentCard>
                        <Empty
                            image="https://gw.alipayobjects.com/zos/antfincdn/ZHrcdLPrvN/empty.svg"
                            imageStyle={{ height: 60 }}
                            description={
                                <h1>Clique no botão abaixo para baixar o relatório</h1>
                            }
                        >
                            <Button type="primary" onClick={handleOnDownloadReport}>Baixar Relatório</Button>
                        </Empty>
                    </ContentCard>
                </Wrapper>
            </LayoutTemplate>
        </>
    );
};

export default ExportReportData;
