import axios, { AxiosError } from "axios";
import type { NextPageContext } from "next";
import Error from "next/error";
import Head from "next/head";
import styled from "styled-components";
import ContentCard from "../../../Components/ContentCard";
import ClientRegistration from "../../../Components/Registration/Client";
import TitleComponent from "../../../Components/Title";
import { Client } from "../../../Models/Client";
import LayoutTemplate from "../../../Templates/Layout";

const Wrapper = styled.div`
    padding: 24px;
`;

interface IUpdateClientProps {
    client?: Client;
}

const UpdateClient = ({ client }: IUpdateClientProps) => {

    if (!client) return <Error statusCode={404} />;
    return (
        <>
            <Head>
                <title>Rental Company</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <LayoutTemplate>
                <Wrapper>
                    <TitleComponent>Atualizar Cadastro de Cliente</TitleComponent>
                    <ContentCard responsive>
                        <ClientRegistration
                            client={client}
                        />
                    </ContentCard>
                </Wrapper>
            </LayoutTemplate>
        </>
    );
};

UpdateClient.getInitialProps = async ({ query }: NextPageContext) => {
    const client = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/client/${query.clientId}`)
        .then(res => res.data)
        .catch((error: AxiosError) => {
            return null;
        });

    return { client }
}

export default UpdateClient;
